# Generated by Django 2.0.1 on 2018-02-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=5000)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Person')),
            ],
        ),
    ]
